version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: project
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  # node:
  #   image: node:18
  #   restart: always
  #   working_dir: /app
  #   volumes:
  #     - ./app:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   command: yarn start

